In [6]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 0.57081989  0.31779638  0.01849863 -1.05058307 -0.14655409]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[ 0.57081989  0.31779638  0.01849863 -1.05058307 -0.14655409]


In [9]:
print(np.dot(a,a.T))

1.55237498177


In [12]:
a = np.random.randn(5,1)
print(a)

[[-0.43045777]
 [ 0.3603055 ]
 [-0.11140863]
 [-0.56136723]
 [ 0.27430646]]


In [13]:
print(np.dot(a,a.T))

[[ 0.18529389 -0.1550963   0.04795671  0.24164489 -0.11807735]
 [-0.1550963   0.12982005 -0.04014114 -0.2022637   0.09883413]
 [ 0.04795671 -0.04014114  0.01241188  0.06254115 -0.03056011]
 [ 0.24164489 -0.2022637   0.06254115  0.31513317 -0.15398666]
 [-0.11807735  0.09883413 -0.03056011 -0.15398666  0.07524403]]


In [14]:
print(a.shape)


(5, 1)


In [19]:
# Dont hesitate the use assert for being sure about shape!
assert(a.shape == (5,1))