In [2]:
import numpy as np

A = np.random.rand(3,4) * 10
print(A)

[[ 9.13901223  9.41616553  3.74065807  5.64084734]
 [ 3.88647724  0.17947555  2.54428128  5.97464784]
 [ 8.84019188  9.93308124  0.79431882  7.20454399]]


In [3]:
cal = A.sum(axis = 0)
print(cal)

[ 21.86568135  19.52872232   7.07925816  18.82003918]


In [4]:
percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[[ 41.79614659  48.2170076   52.83969001  29.97255898]
 [ 17.77432487   0.91903377  35.93994199  31.74620301]
 [ 40.42952854  50.86395863  11.220368    38.28123801]]
